# Generated by Django 5.1.6 on 2025-02-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_scans',
            field=models.IntegerField(default=0),
        ),
    ]
